Flasher.js Getting Started
thingsSDK/guides.thingssdk.com pull request #24
Opened 2017-02-08 17:13 UTC by samjulien

First crack at #1 to get folks up and running on Flasher.js. Fixed some typos and errors I found so re-submitting.

2017-02-09 20:35 UTC, chalkers commented on flasher.js/getting_started.md
> +On Windows, you'll be downloading the binary directly, so you can just move it where you'd like it. On a Mac, you'll be downloading a disk image (.dmg) file. Double-click it and drag the Flasher.js i
The binary is an installer that will create a shortcut in your start menu.

2017-02-09 20:37 UTC, chalkers requested changes
The line about "binary directly" could be misconstrued to mean that it's just the plain-old-binary not an installer.

2017-02-10 04:33 UTC, merged

2017-02-10 04:36 UTC, chalkers commented
Thanks @samjulien - I tweaked the line :)

2017-02-10 05:41 UTC, samjulien commented
Ah thanks, I had a busy afternoon and evening.